openapi: 3.0.1
info:
  title: User API
  version: 1.0.0
paths:
  /generate-qr-code:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToolDto'
      responses:
        '200':
          description: Generated QR Code with name
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QrCodeDto'

components:
  schemas:
    ToolDto:
      type: object
      required:
        - name
        - type
        - toolPlacing
      properties:
        name:
          type: string
          minLength: 2
          maxLength: 50
        description:
          type: string
          maxLength: 200
        size:
          type: string
          enum:
            - Small
            - Medium
            - Large
        color:
          type: string
        quantity:
          type: string
          pattern: '^[1-9][0-9]*$'
        toolPlacing:
          type: string

    QrCodeDto:
      type: object
      properties:
        name:
          type: string
        image:
          type: string