spring:
  application:
    name: Garage QR codes database

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver


logging:
  level:
    root: info